Controllers/ChungChiController.cs
using JobsFinder_Main.Models;
using Microsoft.AspNet.Identity;
using Model.DAO;
using Model.EF;
using System;
using System.Web.Mvc;

namespace JobsFinder_Main.Controllers
{
    public class ChungChiController : Controller
    {
        // GET: ChungChi
        public ActionResult Index()
        {
            return View();
        }

        // GET: ChungChi/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: ChungChi/Create
        [HttpPost]
        public ActionResult Create(ChungChiModel model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var dao = new ChungChiDao();

                var chungChi = new ChungChi
                {
                    TenChungChi = model.TenChungChi,
                    ToChuc = model.ToChuc,
                    ThangXacThuc = model.ThangXacThuc,
                    NamXacThuc = model.NamXacThuc,
                    ThangHetHan = model.ThangHetHan,
                    NamHetHan = model.NamHetHan,
                    Img = model.Img,
                    LienKet = model.LienKet,
                    UserID = User.Identity.GetUserId(),
                    CreatedBy = User.Identity.GetUserName(),
                };

                var result = dao.Insert(chungChi);
                if (result == true)
                {
                    model = new ChungChiModel();
                    TempData["Message"] = "Create successfull!";
                    TempData["MessageType"] = "success";
                    TempData["Type"] = "Success";
                    return RedirectToAction("Index", "Profile", model);
                }
                else
                {
                    TempData["Message"] = "Create unsuccessfull!";
                    TempData["MessageType"] = "error";
                    TempData["Type"] = "Error";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult Update(long id)
        {
            var chungChi = new ChungChiDao().ViewDetail(id);
            return PartialView(chungChi);
        }

        [HttpPost]
        public ActionResult Update(ChungChi model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var dao = new ChungChiDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    if (ModelState.IsValid)
                    {
                        if (!string.IsNullOrEmpty(model.TenChungChi))
                        {
                            entity.TenChungChi = model.TenChungChi;
                        }
                        if (!string.IsNullOrEmpty(model.ToChuc))
                        {
                            entity.ToChuc = model.ToChuc;
                        }
                        if (!string.IsNullOrEmpty(model.ThangXacThuc.ToString()))
                        {
                            entity.ThangXacThuc = model.ThangXacThuc;
                        }
                        if (!string.IsNullOrEmpty(model.NamXacThuc.ToString()))
                        {
                            entity.NamXacThuc = model.NamXacThuc;
                        }
                        if (!string.IsNullOrEmpty(model.ThangHetHan.ToString()))
                        {
                            entity.ThangHetHan = model.ThangHetHan;
                        }
                        if (!string.IsNullOrEmpty(model.NamHetHan.ToString()))
                        {
                            entity.NamHetHan = model.NamHetHan;
                        }
                        entity.ModifiedBy = User.Identity.Name;
                        entity.ModifiedDate = DateTime.Now;

                        var result = dao.Update(entity);
                        if (result)
                        {
                            TempData["Message"] = "Update successfull!";
                            TempData["MessageType"] = "success";
                            TempData["Type"] = "Success";
                            return RedirectToAction("Index", "Profile");
                        }
                        else
                        {
                            TempData["Message"] = "Update unsuccessfull!";
                            TempData["MessageType"] = "error";
                            TempData["Type"] = "Error";
                            return RedirectToAction("Index", "Profile");
                        }
                    }
                    else
                    {
                        TempData["Message"] = "An error occurred! Please try again!";
                        TempData["MessageType"] = "warning";
                        TempData["Type"] = "Warning";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "An error occurred! Please try again";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Warning";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult DeleteConfirm(long id)
        {
            var chungChi = new ChungChiDao().ViewDetail(id);
            return PartialView(chungChi);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(ChungChi model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var dao = new ChungChiDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    var result = dao.Delete(entity);
                    if (result)
                    {
                        TempData["Message"] = "Delete successfull!";
                        TempData["MessageType"] = "success";
                        TempData["Type"] = "Success";
                        return RedirectToAction("Index", "Profile");
                    }
                    else
                    {
                        TempData["Message"] = "Delete unsuccessfull!";
                        TempData["MessageType"] = "error";
                        TempData["Type"] = "Error";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "An error occurred! Please try again!";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Warning";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
    }
}

Views/ChungChi/Create.cshtml
@model JobsFinder_Main.Models.ChungChiModel

@if (User.Identity.IsAuthenticated)
{
    <div id="formChungChi" class="p-4 form-profile">
        @using (Html.BeginForm("Create", "ChungChi", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h5 class="m-0">Certificate</h5>
                <hr class="my-3" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group mb-4">
                    <p class="label-title">Certificate name</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.TenChungChi, new { @class = "form-control", @placeholder = "Certificate name" })
                        @Html.ValidationMessageFor(model => model.TenChungChi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Organization</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.ToChuc, new { @class = "form-control", @placeholder = "Organization" })
                        @Html.ValidationMessageFor(model => model.ToChuc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <label class="mb-4">
                    <input type="checkbox" id="chungChiCheckbox" class="checkbox" />
                    The certificate does not have an expiration date.
                </label>

                <div class="d-flex flex-row justify-content-between">
                    <div id="chungChiBatDau" class="d-flex justify-content-between" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Validity period</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangXacThuc, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Select month", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ThangXacThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title" style="opacity: 0;">Start year</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        int currentYear = DateTime.Now.Year;
                                        int startYear = currentYear - 100;
                                        List<SelectListItem> years = new List<SelectListItem>();
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamXacThuc, years, "Select year", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.NamXacThuc, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamXacThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div id="chungChiKetThuc" class="d-flex justify-content-between boxKetThuc" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Expiration date</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangHetHan, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Select month", new { @class = "form-control thangKetThuc" })
                                @Html.ValidationMessageFor(model => model.ThangHetHan, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title" style="opacity: 0;">Finish year</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamHetHan, years, "Select year", new { @class = "form-control namKetThuc" })
                                    @Html.ValidationMessageFor(model => model.NamHetHan, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamHetHan, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group mb-2">
                    <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                        <input type="submit" value="Complete" class="btn btn-primary" style="border-radius: 4px;" />
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    { Html.RenderAction("Login", "User"); }
}

Views/ChungChi/DeleteConfirm.cshtml
@model Model.EF.ChungChi

@if (!User.Identity.IsAuthenticated)
{
    { Html.RenderAction("Login", "User"); }
}
else
{
    <div id="formDeleteChungChi@(Model.ID)" class="p-4 form-profile form-delete">
        <div class="d-flex flex-column align-items-center">
            <img style="width: 120px; height: 120px; object-fit: cover;" src="~/Assets/Client/JobsFinder/img/DeleteIcon.png" />
            @using (Html.BeginForm("DeleteConfirm", "ChungChi", FormMethod.Post, new { @class = "box-delete" }))
            {
                @Html.AntiForgeryToken()

                <p style="font-size:  16px; font-weight: 600;">Do you want to delete this item?</p>

                <div class="form-actions no-color d-flex justify-content-between" style="width: 100%">
                    <button type="reset" class="btn btn-outline-primary btn-cance" style="border-radius: 4px; width: 45%;">Cancle</button>
                    <button type="submit" class="btn btn-danger" style="border-radius: 4px; width: 45%;">Delete</button>
                </div>
            }
        </div>
    </div>

    <style>
        .form-delete {
            width: 400px !important;
            margin-top: 200px !important;
        }

            .form-delete .box-delete {
                width: 100%;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
            }
    </style>
}

Views/ChungChi/Update.cshtml
@model Model.EF.ChungChi

@if (User.Identity.IsAuthenticated)
{
    <div id="formUpdateChungChi@(Model.ID)" class="p-4 form-profile">
        @using (Html.BeginForm("Update", "ChungChi", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h5 class="m-0">Certificate</h5>
                <hr class="my-3" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group mb-4">
                    <p class="label-title">Certificate name</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.TenChungChi, new { @class = "form-control", @placeholder = "Certificate name" })
                        @Html.ValidationMessageFor(model => model.TenChungChi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Organization</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.ToChuc, new { @class = "form-control", @placeholder = "Organization" })
                        @Html.ValidationMessageFor(model => model.ToChuc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <label class="mb-4">
                    <input type="checkbox" id="chungChiCheckbox" class="checkbox" />
                    The certificate does not have an expiration date.
                </label>

                <div class="d-flex flex-row justify-content-between">
                    <div id="kinhNghiemnBatDau" class="d-flex justify-content-between" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Validity period</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangXacThuc, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Select month", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ThangXacThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title" style="opacity: 0;">Start year</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        int currentYear = DateTime.Now.Year;
                                        int startYear = currentYear - 100;
                                        List<SelectListItem> years = new List<SelectListItem>();
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamXacThuc, years, "Select year", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.NamXacThuc, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamXacThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div id="kinhNghiemKetThuc" class="d-flex justify-content-between boxKetThuc" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Expiration date</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangHetHan, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Select month", new { @class = "form-control thangKetThuc" })
                                @Html.ValidationMessageFor(model => model.ThangHetHan, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title" style="opacity: 0;">Finish year</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamHetHan, years, "Select year", new { @class = "form-control namKetThuc" })
                                    @Html.ValidationMessageFor(model => model.NamHetHan, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamHetHan, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group mb-2">
                    <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                        <input type="submit" value="Complete" class="btn btn-primary" style="border-radius: 4px;" />
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    { Html.RenderAction("Login", "User"); }
}