Controllers/KyNangController.cs
using JobsFinder_Main.Common;
using JobsFinder_Main.Models;
using Microsoft.AspNet.Identity;
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobsFinder_Main.Controllers
{
    public class KyNangController : Controller
    {
        // GET: KyNang
        public ActionResult Index()
        {
            return View();
        }

        // GET: KyNang/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: KyNang/Create
        [HttpPost]
        public ActionResult Create(KyNangModel model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var dao = new KyNangDao();

                var kyNang = new KyNang
                {
                    TenKyNang = model.TenKyNang,
                    DanhGia = model.DanhGia,
                    Caption = model.Caption,
                    MoTaChiTiet = model.MoTaChiTiet,
                    UserID = User.Identity.GetUserId(),
                    CreatedBy = User.Identity.GetUserName()
                };

                var result = dao.Insert(kyNang);
                if (result == true)
                {
                    model = new KyNangModel();
                    TempData["Message"] = "Create successfull!";
                    TempData["MessageType"] = "success";
                    TempData["Type"] = "Success";
                    return RedirectToAction("Index", "Profile", model);
                }
                else
                {
                    TempData["Message"] = "Create unsuccessfull!";
                    TempData["MessageType"] = "error";
                    TempData["Type"] = "Error";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult Update(long id)
        {
            var kyNang = new KyNangDao().ViewDetail(id);
            return PartialView(kyNang);
        }

        [HttpPost]
        public ActionResult Update(KyNang model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var dao = new KyNangDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    if (ModelState.IsValid)
                    {
                        if (!string.IsNullOrEmpty(model.TenKyNang))
                        {
                            entity.TenKyNang = model.TenKyNang;
                        }
                        if (!string.IsNullOrEmpty(model.DanhGia.ToString()))
                        {
                            entity.DanhGia = model.DanhGia;
                        }
                        if (!string.IsNullOrEmpty(model.Caption.ToString()))
                        {
                            entity.Caption = model.Caption;
                        }
                        if (!string.IsNullOrEmpty(model.MoTaChiTiet))
                        {
                            entity.MoTaChiTiet = model.MoTaChiTiet;
                        }
                        entity.ModifiedBy = User.Identity.Name;
                        entity.ModifiedDate = DateTime.Now;

                        var result = dao.Update(entity);
                        if (result)
                        {
                            TempData["Message"] = "Update successfull!";
                            TempData["MessageType"] = "success";
                            TempData["Type"] = "Success";
                            return RedirectToAction("Index", "Profile");
                        }
                        else
                        {
                            TempData["Message"] = "Update unsuccessfull!";
                            TempData["MessageType"] = "error";
                            TempData["Type"] = "Error";
                            return RedirectToAction("Index", "Profile");
                        }
                    }
                    else
                    {
                        TempData["Message"] = "An error occurred! Please try again!";
                        TempData["MessageType"] = "warning";
                        TempData["Type"] = "Warning";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "An error occurred! Please try again";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Warning";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult DeleteConfirm(long id)
        {
            var kyNang = new KyNangDao().ViewDetail(id);
            return PartialView(kyNang);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(KyNang model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var dao = new KyNangDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    var result = dao.Delete(entity);
                    if (result)
                    {
                        TempData["Message"] = "Delete successfull!";
                        TempData["MessageType"] = "success";
                        TempData["Type"] = "Success";
                        return RedirectToAction("Index", "Profile");
                    }
                    else
                    {
                        TempData["Message"] = "Delete unsuccessfull!";
                        TempData["MessageType"] = "error";
                        TempData["Type"] = "Error";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "An error occurred! Please try again!";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Warning";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
    }
}

Views/KyNang/Create.cshtml
@model JobsFinder_Main.Models.KyNangModel

@if (User.Identity.IsAuthenticated)
{
    <div id="formKyNang" class="p-4 form-profile">
        @using (Html.BeginForm("Create", "KyNang", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h5 class="m-0">Skills</h5>
                <hr class="my-3" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group mb-4">
                    <p class="label-title">Skill name</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.TenKyNang, new { @class = "form-control", @placeholder = "Enter a skill name" })
                        @Html.ValidationMessageFor(model => model.TenKyNang, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Review</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.DanhGia, new { @class = "form-control", @type = "hidden" })
                        @Html.TextBoxFor(model => model.Caption, new { @class = "form-control", @type = "hidden" })
                        @Html.ValidationMessageFor(model => model.DanhGia, "", new { @class = "text-danger" })
                    </div>
                    <div class="box-rating d-flex flex-row">
                        <i class="bi bi-star"></i>
                        <i class="bi bi-star"></i>
                        <i class="bi bi-star"></i>
                        <i class="bi bi-star"></i>
                        <i class="bi bi-star"></i>
                    </div>
                    <p class="rating-caption" style="height: 26px;">Select the corresponding number of stars for your skill level</p>
                </div>

                <style>
                    .box-rating i {
                        font-size: 20px;
                        padding: 4px;
                        margin-right: 8px;
                    }

                        .box-rating i.bi-star-fill {
                            color: gold;
                        }
                </style>

                <script>
                    var stars = document.querySelectorAll(".bi-star");
                    var inputDanhGia = document.getElementById("DanhGia");
                    var ratingCaption = document.querySelector(".rating-caption");
                    var caption = document.getElementById("Caption");
                    var captions = [
                        "Just heard about it",
                        "No completed product yet",
                        "Completed product available",
                        "Completed product within the same team",
                        "Proficient"
                    ];

                    stars.forEach(function (star, index) {
                        star.addEventListener("click", function () {
                            var rating = index + 1;
                            inputDanhGia.value = rating;
                            updateStars();
                            ratingCaption.textContent = captions[rating - 1];
                            caption.value = ratingCaption.textContent;
                        });

                        star.addEventListener("mouseover", function () {
                            for (var i = 0; i <= index; i++) {
                                stars[i].classList.remove("bi-star");
                                stars[i].classList.add("bi-star-fill");
                            }

                            for (var j = index + 1; j < stars.length; j++) {
                                stars[j].classList.add("bi-star");
                                stars[j].classList.remove("bi-star-fill");
                            }
                            ratingCaption.textContent = captions[index];
                        });

                        star.addEventListener("mouseout", function () {
                            updateStars();
                            var rating = parseInt(inputDanhGia.value);
                            ratingCaption.textContent = captions[rating - 1];
                        });
                    });

                    function updateStars() {
                        stars.forEach(function (star, index) {
                            star.classList.remove("bi-star-fill");
                            star.classList.add("bi-star");
                        });

                        var rating = parseInt(inputDanhGia.value);
                        for (var i = 0; i < rating; i++) {
                            stars[i].classList.remove("bi-star");
                            stars[i].classList.add("bi-star-fill");
                        }
                    }
                </script>

                <div class="form-group">
                    <p class="label-title">Description</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextAreaFor(model => model.MoTaChiTiet, new { @class = "form-control pt-2", @placeholder = "Detailed description" })
                        @Html.ValidationMessageFor(model => model.MoTaChiTiet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-2">
                    <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                        <input type="submit" value="Complete" class="btn btn-primary" style="border-radius: 4px;" />
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    { Html.RenderAction("Login", "User"); }
}

Views/KyNang/DeleteConfirm.cshtml
@model Model.EF.KyNang

@if (!User.Identity.IsAuthenticated)
{
    { Html.RenderAction("Login", "User"); }
}
else
{
    <div id="formDeleteKyNang@(Model.ID)" class="p-4 form-profile form-delete">
        <div class="d-flex flex-column align-items-center">
            <img style="width: 120px; height: 120px; object-fit: cover;" src="~/Assets/Client/JobsFinder/img/DeleteIcon.png" />
            @using (Html.BeginForm("DeleteConfirm", "KyNang", FormMethod.Post, new { @class = "box-delete" }))
            {
                @Html.AntiForgeryToken()

                <p style="font-size:  16px; font-weight: 600;">Do you want to delete this item?</p>

                <div class="form-actions no-color d-flex justify-content-between" style="width: 100%">
                    <button type="reset" class="btn btn-outline-primary btn-cance" style="border-radius: 4px; width: 45%;">Cancle</button>
                    <button type="submit" class="btn btn-danger" style="border-radius: 4px; width: 45%;">Delete</button>
                </div>
            }
        </div>
    </div>

    <style>
        .form-delete {
            width: 400px !important;
            margin-top: 200px !important;
        }

            .form-delete .box-delete {
                width: 100%;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
            }
    </style>
}

Views/KyNang/Update.cshtml
@model Model.EF.KyNang

@if (User.Identity.IsAuthenticated)
{
    <div id="formUpdateKyNang@(Model.ID)" class="p-4 form-profile">
        @using (Html.BeginForm("Update", "KyNang", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h5 class="m-0">Skills</h5>
                <hr class="my-3" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group mb-4">
                    <p class="label-title">Skill name</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.TenKyNang, new { @class = "form-control", @placeholder = "Enter a skill name" })
                        @Html.ValidationMessageFor(model => model.TenKyNang, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Review</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.DanhGia, new { @class = "form-control", @type = "hidden" })
                        @Html.TextBoxFor(model => model.Caption, new { @class = "form-control", @type = "hidden" })
                        @Html.ValidationMessageFor(model => model.DanhGia, "", new { @class = "text-danger" })
                    </div>
                    <div class="box-rating d-flex flex-row">
                        <i class="bi bi-star"></i>
                        <i class="bi bi-star"></i>
                        <i class="bi bi-star"></i>
                        <i class="bi bi-star"></i>
                        <i class="bi bi-star"></i>
                    </div>
                    <p class="rating-caption" style="height: 26px;">Select the corresponding number of stars for your skill level</p>
                </div>

                <style>
                    .box-rating i {
                        font-size: 20px;
                        padding: 4px;
                        margin-right: 8px;
                    }

                        .box-rating i.bi-star-fill {
                            color: gold;
                        }
                </style>

                <script>
                    var stars = document.querySelectorAll(".bi-star");
                    var inputDanhGia = document.getElementById("DanhGia");
                    var ratingCaption = document.querySelector(".rating-caption");
                    var caption = document.getElementById("Caption");
                    var captions = [
                        "Just heard about it",
                        "No completed product yet",
                        "Completed product available",
                        "Completed product within the same team",
                        "Proficient"
                    ];

                    stars.forEach(function (star, index) {
                        star.addEventListener("click", function () {
                            var rating = index + 1;
                            inputDanhGia.value = rating;
                            updateStars();
                            ratingCaption.textContent = captions[rating - 1];
                            caption.value = ratingCaption.textContent;
                        });

                        star.addEventListener("mouseover", function () {
                            for (var i = 0; i <= index; i++) {
                                stars[i].classList.remove("bi-star");
                                stars[i].classList.add("bi-star-fill");
                            }

                            for (var j = index + 1; j < stars.length; j++) {
                                stars[j].classList.add("bi-star");
                                stars[j].classList.remove("bi-star-fill");
                            }
                            ratingCaption.textContent = captions[index];
                        });

                        star.addEventListener("mouseout", function () {
                            updateStars();
                            var rating = parseInt(inputDanhGia.value);
                            ratingCaption.textContent = captions[rating - 1];
                        });
                    });

                    function updateStars() {
                        stars.forEach(function (star, index) {
                            star.classList.remove("bi-star-fill");
                            star.classList.add("bi-star");
                        });

                        var rating = parseInt(inputDanhGia.value);
                        for (var i = 0; i < rating; i++) {
                            stars[i].classList.remove("bi-star");
                            stars[i].classList.add("bi-star-fill");
                        }
                    }
                </script>

                <div class="form-group">
                    <p class="label-title">Description</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextAreaFor(model => model.MoTaChiTiet, new { @class = "form-control pt-2", @placeholder = "Detailed description" })
                        @Html.ValidationMessageFor(model => model.MoTaChiTiet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-2">
                    <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                        <input type="submit" value="Complete" class="btn btn-primary" style="border-radius: 4px;" />
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    { Html.RenderAction("Login", "User"); }
}