Controllers/HoatDongController.cs
using JobsFinder_Main.Common;
using JobsFinder_Main.Models;
using Microsoft.AspNet.Identity;
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobsFinder_Main.Controllers
{
    public class HoatDongController : Controller
    {
        // GET: HoatDong
        public ActionResult Index()
        {
            return View();
        }

        // GET: HoatDong/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: HoatDong/Create
        [HttpPost]
        public ActionResult Create(HoatDongModel model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var dao = new HoatDongDao();

                var hoatDong = new HoatDong
                {
                    TenHoatDong = model.TenHoatDong,
                    ViTriThamGia = model.ViTriThamGia,
                    ThangThamGia = model.ThangThamGia,
                    NamThamGia = model.NamThamGia,
                    ThangKetThuc = model.ThangKetThuc,
                    NamKetThuc = model.NamKetThuc,
                    MoTaChiTiet = model.MoTaChiTiet,
                    Img = model.Img,
                    LienKet = model.LienKet,
                    UserID = User.Identity.GetUserId(),
                    CreatedBy = User.Identity.GetUserName()
                };

                var result = dao.Insert(hoatDong);
                if (result == true)
                {
                    model = new HoatDongModel();
                    TempData["Message"] = "Create successfull!";
                    TempData["MessageType"] = "success";
                    TempData["Type"] = "Success";
                    return RedirectToAction("Index", "Profile", model);
                }
                else
                {
                    TempData["Message"] = "Create unsuccessfull!";
                    TempData["MessageType"] = "error";
                    TempData["Type"] = "Error";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult Update(long id)
        {
            var hoatDong = new HoatDongDao().ViewDetail(id);
            return PartialView(hoatDong);
        }

        [HttpPost]
        public ActionResult Update(HoatDong model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var dao = new HoatDongDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    if (ModelState.IsValid)
                    {
                        if (!string.IsNullOrEmpty(model.TenHoatDong))
                        {
                            entity.TenHoatDong = model.TenHoatDong;
                        }
                        if (!string.IsNullOrEmpty(model.ViTriThamGia))
                        {
                            entity.ViTriThamGia = model.ViTriThamGia;
                        }
                        if (!string.IsNullOrEmpty(model.ThangThamGia.ToString()))
                        {
                            entity.ThangThamGia = model.ThangThamGia;
                        }
                        if (!string.IsNullOrEmpty(model.NamThamGia.ToString()))
                        {
                            entity.NamThamGia = model.NamThamGia;
                        }
                        if (!string.IsNullOrEmpty(model.ThangKetThuc.ToString()))
                        {
                            entity.ThangKetThuc = model.ThangKetThuc;
                        }
                        if (!string.IsNullOrEmpty(model.NamKetThuc.ToString()))
                        {
                            entity.NamKetThuc = model.NamKetThuc;
                        }
                        if (!string.IsNullOrEmpty(model.MoTaChiTiet))
                        {
                            entity.MoTaChiTiet = model.MoTaChiTiet;
                        }
                        entity.ModifiedBy = User.Identity.Name;
                        entity.ModifiedDate = DateTime.Now;

                        var result = dao.Update(entity);
                        if (result)
                        {
                            TempData["Message"] = "Update successfull!";
                            TempData["MessageType"] = "success";
                            TempData["Type"] = "Success";
                            return RedirectToAction("Index", "Profile");
                        }
                        else
                        {
                            TempData["Message"] = "Update unsuccessfull!";
                            TempData["MessageType"] = "error";
                            TempData["Type"] = "Error";
                            return RedirectToAction("Index", "Profile");
                        }
                    }
                    else
                    {
                        TempData["Message"] = "An error occurred! Please try again!";
                        TempData["MessageType"] = "warning";
                        TempData["Type"] = "Warning";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "An error occurred! Please try again";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Warning";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult DeleteConfirm(long id)
        {
            var hoatDong = new HoatDongDao().ViewDetail(id);
            return PartialView(hoatDong);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(HoatDong model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var dao = new HoatDongDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    var result = dao.Delete(entity);
                    if (result)
                    {
                        TempData["Message"] = "Delete successfull!";
                        TempData["MessageType"] = "success";
                        TempData["Type"] = "Success";
                        return RedirectToAction("Index", "Profile");
                    }
                    else
                    {
                        TempData["Message"] = "Delete unsuccessfull!";
                        TempData["MessageType"] = "error";
                        TempData["Type"] = "Error";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "An error occurred! Please try again!";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Warning";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
    }
}

Views/HoatDong/Create.cshtml
@model JobsFinder_Main.Models.HoatDongModel

@if (User.Identity.IsAuthenticated)
{
    <div id="formHoatDong" class="p-4 form-profile">
        @using (Html.BeginForm("Create", "HoatDong", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h5 class="m-0">Volunteer & social activities</h5>
                <hr class="my-3" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group mb-4">
                    <p class="label-title">Activity name</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.TenHoatDong, new { @class = "form-control", @placeholder = "Activity name" })
                        @Html.ValidationMessageFor(model => model.TenHoatDong, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Position participated</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.ViTriThamGia, new { @class = "form-control", @placeholder = "Position participated" })
                        @Html.ValidationMessageFor(model => model.ViTriThamGia, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="d-flex flex-row justify-content-between">
                    <div id="kinhNghiemnBatDau" class="d-flex justify-content-between" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Start month</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangThamGia, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Select month", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ThangThamGia, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title">Star year</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        int currentYear = DateTime.Now.Year;
                                        int startYear = currentYear - 100;
                                        List<SelectListItem> years = new List<SelectListItem>();
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamThamGia, years, "Select year", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.NamThamGia, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamThamGia, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div id="kinhNghiemKetThuc" class="d-flex justify-content-between boxKetThuc" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Finish month</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangKetThuc, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Select month", new { @class = "form-control thangKetThuc" })
                                @Html.ValidationMessageFor(model => model.ThangKetThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title">Finish year</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamKetThuc, years, "Select year", new { @class = "form-control namKetThuc" })
                                    @Html.ValidationMessageFor(model => model.NamKetThuc, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamKetThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <p class="label-title">Description</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextAreaFor(model => model.MoTaChiTiet, new { @class = "form-control pt-2", @placeholder = "Mô tả chi tiết" })
                        @Html.ValidationMessageFor(model => model.MoTaChiTiet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-2">
                    <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                        <input type="submit" value="Complete" class="btn btn-primary" style="border-radius: 4px;" />
                    </div>
                </div>
            </div>
        }
    </div>
}

else
{
    { Html.RenderAction("Login", "User"); }
}

Views/HoatDong/DeleteConfirm.cshtml
@model Model.EF.HoatDong

@if (!User.Identity.IsAuthenticated)
{
    { Html.RenderAction("Login", "User"); }
}
else
{
    <div id="formDeleteHoatDong@(Model.ID)" class="p-4 form-profile form-delete">
        <div class="d-flex flex-column align-items-center">
            <img style="width: 120px; height: 120px; object-fit: cover;" src="~/Assets/Client/JobsFinder/img/DeleteIcon.png" />
            @using (Html.BeginForm("DeleteConfirm", "HoatDong", FormMethod.Post, new { @class = "box-delete" }))
            {
                @Html.AntiForgeryToken()

                <p style="font-size:  16px; font-weight: 600;">Do you want to delete this item?</p>

                <div class="form-actions no-color d-flex justify-content-between" style="width: 100%">
                    <button type="reset" class="btn btn-outline-primary btn-cance" style="border-radius: 4px; width: 45%;">Cancle</button>
                    <button type="submit" class="btn btn-danger" style="border-radius: 4px; width: 45%;">Delete</button>
                </div>
            }
        </div>
    </div>

    <style>
        .form-delete {
            width: 400px !important;
            margin-top: 200px !important;
        }

            .form-delete .box-delete {
                width: 100%;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
            }
    </style>
}

Views/HoatDong/Update.cshtml
@model Model.EF.HoatDong

@if (User.Identity.IsAuthenticated)
{
    <div id="formUpdateHoatDong@(Model.ID)" class="p-4 form-profile">
        @using (Html.BeginForm("Update", "HoatDong", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h5 class="m-0">Volunteer & social activities</h5>
                <hr class="my-3" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group mb-4">
                    <p class="label-title">Activity name</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.TenHoatDong, new { @class = "form-control", @placeholder = "Activity name" })
                        @Html.ValidationMessageFor(model => model.TenHoatDong, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Position participated</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.ViTriThamGia, new { @class = "form-control", @placeholder = "Position participated" })
                        @Html.ValidationMessageFor(model => model.ViTriThamGia, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="d-flex flex-row justify-content-between">
                    <div id="kinhNghiemnBatDau" class="d-flex justify-content-between" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Start month</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangThamGia, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Select month", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ThangThamGia, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title">Star year</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        int currentYear = DateTime.Now.Year;
                                        int startYear = currentYear - 100;
                                        List<SelectListItem> years = new List<SelectListItem>();
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamThamGia, years, "Select year", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.NamThamGia, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamThamGia, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div id="kinhNghiemKetThuc" class="d-flex justify-content-between boxKetThuc" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Finish month</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangKetThuc, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Select month", new { @class = "form-control thangKetThuc" })
                                @Html.ValidationMessageFor(model => model.ThangKetThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title">Finish year</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamKetThuc, years, "Select year", new { @class = "form-control namKetThuc" })
                                    @Html.ValidationMessageFor(model => model.NamKetThuc, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamKetThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <p class="label-title">Description</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextAreaFor(model => model.MoTaChiTiet, new { @class = "form-control pt-2", @placeholder = "Mô tả chi tiết" })
                        @Html.ValidationMessageFor(model => model.MoTaChiTiet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-2">
                    <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                        <input type="submit" value="Complete" class="btn btn-primary" style="border-radius: 4px;" />
                    </div>
                </div>
            </div>
        }
    </div>
}

else
{
    { Html.RenderAction("Login", "User"); }
}