Controllers/DuAnController.cs
using JobsFinder_Main.Common;
using JobsFinder_Main.Models;
using Microsoft.AspNet.Identity;
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobsFinder_Main.Controllers
{
    public class DuAnController : Controller
    {
        // GET: DuAn
        public ActionResult Index()
        {
            return View();
        }

        // GET: DuAn/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: DuAn/Create
        [HttpPost]
        public ActionResult Create(DuAnModel model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var dao = new DuAnDao();

                var duAn = new DuAn
                {
                    TenDuAn = model.TenDuAn,
                    TenKhachHang = model.TenKhachHang,
                    SoThanhVien = model.SoThanhVien,
                    ViTri = model.ViTri,
                    NhiemVu = model.NhiemVu,
                    CongNgheSuDung = model.CongNgheSuDung,
                    ThangBatDau = model.ThangBatDau,
                    NamBatDau = model.NamBatDau,
                    ThangKetThuc = model.ThangKetThuc,
                    NamKetThuc = model.NamKetThuc,
                    MoTaChiTiet = model.MoTaChiTiet,
                    Img = model.Img,
                    LienKet = model.LienKet,
                    UserID = User.Identity.GetUserId(),
                    CreatedBy = User.Identity.GetUserName(),
                };

                var result = dao.Insert(duAn);
                if (result == true)
                {
                    model = new DuAnModel();
                    TempData["Message"] = "Create successfull!";
                    TempData["MessageType"] = "success";
                    TempData["Type"] = "Success";
                    return RedirectToAction("Index", "Profile", model);
                }
                else
                {
                    TempData["Message"] = "Create unsuccessfull!";
                    TempData["MessageType"] = "error";
                    TempData["Type"] = "Error";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult Update(long id)
        {
            var duAn = new DuAnDao().ViewDetail(id);
            return PartialView(duAn);
        }

        [HttpPost]
        public ActionResult Update(DuAn model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var dao = new DuAnDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    if (ModelState.IsValid)
                    {
                        if (!string.IsNullOrEmpty(model.TenDuAn))
                        {
                            entity.TenDuAn = model.TenDuAn;
                        }
                        if (!string.IsNullOrEmpty(model.TenKhachHang))
                        {
                            entity.TenKhachHang = model.TenKhachHang;
                        }
                        if (!string.IsNullOrEmpty(model.ViTri))
                        {
                            entity.ViTri = model.ViTri;
                        }
                        if (!string.IsNullOrEmpty(model.NhiemVu))
                        {
                            entity.NhiemVu = model.NhiemVu;
                        }
                        if (!string.IsNullOrEmpty(model.CongNgheSuDung))
                        {
                            entity.CongNgheSuDung = model.CongNgheSuDung;
                        }
                        if (!string.IsNullOrEmpty(model.SoThanhVien.ToString()))
                        {
                            entity.SoThanhVien = model.SoThanhVien;
                        }
                        if (!string.IsNullOrEmpty(model.ThangBatDau.ToString()))
                        {
                            entity.ThangBatDau = model.ThangBatDau;
                        }
                        if (!string.IsNullOrEmpty(model.NamBatDau.ToString()))
                        {
                            entity.NamBatDau = model.NamBatDau;
                        }
                        if (!string.IsNullOrEmpty(model.ThangKetThuc.ToString()))
                        {
                            entity.ThangKetThuc = model.ThangKetThuc;
                        }
                        if (!string.IsNullOrEmpty(model.NamKetThuc.ToString()))
                        {
                            entity.NamKetThuc = model.NamKetThuc;
                        }
                        if (!string.IsNullOrEmpty(model.MoTaChiTiet))
                        {
                            entity.MoTaChiTiet = model.MoTaChiTiet;
                        }
                        entity.ModifiedBy = User.Identity.Name;
                        entity.ModifiedDate = DateTime.Now;

                        var result = dao.Update(entity);
                        if (result)
                        {
                            TempData["Message"] = "Update successfull!";
                            TempData["MessageType"] = "success";
                            TempData["Type"] = "Success";
                            return RedirectToAction("Index", "Profile");
                        }
                        else
                        {
                            TempData["Message"] = "Update unsuccessfull!";
                            TempData["MessageType"] = "error";
                            TempData["Type"] = "Error";
                            return RedirectToAction("Index", "Profile");
                        }
                    }
                    else
                    {
                        TempData["Message"] = "An error occurred! Please try again!";
                        TempData["MessageType"] = "warning";
                        TempData["Type"] = "Warning";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "An error occurred! Please try again";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Warning";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult DeleteConfirm(long id)
        {
            var duAn = new DuAnDao().ViewDetail(id);
            return PartialView(duAn);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(DuAn model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var dao = new DuAnDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    var result = dao.Delete(entity);
                    if (result)
                    {
                        TempData["Message"] = "Delete successfull!";
                        TempData["MessageType"] = "success";
                        TempData["Type"] = "Success";
                        return RedirectToAction("Index", "Profile");
                    }
                    else
                    {
                        TempData["Message"] = "Delete unsuccessfull!";
                        TempData["MessageType"] = "error";
                        TempData["Type"] = "Error";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "An error occurred! Please try again!";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Warning";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
    }
}

Views/DuAn/Create.cshtml
@model JobsFinder_Main.Models.DuAnModel

@if (User.Identity.IsAuthenticated)
{
    <div id="formDuAn" class="p-4 form-profile">
        @using (Html.BeginForm("Create", "DuAn", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h5 class="m-0">Project</h5>
                <hr class="my-3" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group mb-4">
                    <p class="label-title">Project name</p>
                    <div class="col-md-10" style="width: 100%">
                        @Html.TextBoxFor(model => model.TenDuAn, new { @class = "form-control", @placeholder = "Project name" })
                        @Html.ValidationMessageFor(model => model.TenDuAn, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Customer name</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.TenKhachHang, new { @class = "form-control", @placeholder = "Customer name" })
                        @Html.ValidationMessageFor(model => model.TenKhachHang, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Number of members</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.SoThanhVien, new { @class = "form-control", @placeholder = "Number of members", @type = "number" })
                        @Html.ValidationMessageFor(model => model.SoThanhVien, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Position</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.ViTri, new { @class = "form-control", @placeholder = "Position within the team" })
                        @Html.ValidationMessageFor(model => model.ViTri, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Tasks</p>
                    <div class="col-md-10" style="width:100%;">
                        @Html.TextBoxFor(model => model.NhiemVu, new { @class = "form-control", @placeholder = "Tasks" })
                        @Html.ValidationMessageFor(model => model.NhiemVu, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Technologies used</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.CongNgheSuDung, new { @class = "form-control", @placeholder = "NodeJS, ASP.NET,..." })
                        @Html.ValidationMessageFor(model => model.CongNgheSuDung, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="d-flex flex-row justify-content-between">
                    <div id="kinhNghiemnBatDau" class="d-flex justify-content-between" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Month start</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangBatDau, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Select month", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ThangBatDau, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title">Start year</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        int currentYear = DateTime.Now.Year;
                                        int startYear = currentYear - 100;
                                        List<SelectListItem> years = new List<SelectListItem>();
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamBatDau, years, "Select year", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.NamBatDau, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamBatDau, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div id="kinhNghiemKetThuc" class="d-flex justify-content-between boxKetThuc" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Finish month</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangKetThuc, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Select month", new { @class = "form-control thangKetThuc" })
                                @Html.ValidationMessageFor(model => model.ThangKetThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title">Finish year</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamKetThuc, years, "Select year", new { @class = "form-control namKetThuc" })
                                    @Html.ValidationMessageFor(model => model.NamKetThuc, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamKetThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <p class="label-title">Description</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextAreaFor(model => model.MoTaChiTiet, new { @class = "form-control pt-2", @placeholder = "Detailed description" })
                        @Html.ValidationMessageFor(model => model.MoTaChiTiet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-2">
                    <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                        <input type="submit" value="Complete" class="btn btn-primary" style="border-radius: 4px;" />
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    { Html.RenderAction("Login", "User"); }
}

Views/DuAn/DeleteConfirm.cshtml
@model Model.EF.DuAn

@if (!User.Identity.IsAuthenticated)
{
    { Html.RenderAction("Login", "User"); }
}
else
{
    <div id="formDeleteDuAn@(Model.ID)" class="p-4 form-profile form-delete">
        <div class="d-flex flex-column align-items-center">
            <img style="width: 120px; height: 120px; object-fit: cover;" src="~/Assets/Client/JobsFinder/img/DeleteIcon.png" />
            @using (Html.BeginForm("DeleteConfirm", "DuAn", FormMethod.Post, new { @class = "box-delete" }))
            {
                @Html.AntiForgeryToken()

                <p style="font-size:  16px; font-weight: 600;">Do you want to delete this item?</p>

                <div class="form-actions no-color d-flex justify-content-between" style="width: 100%">
                    <button type="reset" class="btn btn-outline-primary btn-cance" style="border-radius: 4px; width: 45%;">Cancle</button>
                    <button type="submit" class="btn btn-danger" style="border-radius: 4px; width: 45%;">Delete</button>
                </div>
            }
        </div>
    </div>

    <style>
        .form-delete {
            width: 400px !important;
            margin-top: 200px !important;
        }

            .form-delete .box-delete {
                width: 100%;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
            }
    </style>
}

Views/DuAn/Update.cshtml
@model Model.EF.DuAn

@if (User.Identity.IsAuthenticated)
{
    <div id="formUpdateDuAn@(Model.ID)" class="p-4 form-profile">
        @using (Html.BeginForm("Update", "DuAn", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h5 class="m-0">Project</h5>
                <hr class="my-3" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group mb-4">
                    <p class="label-title">Project name</p>
                    <div class="col-md-10" style="width: 100%">
                        @Html.TextBoxFor(model => model.TenDuAn, new { @class = "form-control", @placeholder = "Project name" })
                        @Html.ValidationMessageFor(model => model.TenDuAn, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Customer name</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.TenKhachHang, new { @class = "form-control", @placeholder = "Customer name" })
                        @Html.ValidationMessageFor(model => model.TenKhachHang, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Number of members</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.SoThanhVien, new { @class = "form-control", @placeholder = "Number of members", @type = "number" })
                        @Html.ValidationMessageFor(model => model.SoThanhVien, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Position</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.ViTri, new { @class = "form-control", @placeholder = "Position within the team" })
                        @Html.ValidationMessageFor(model => model.ViTri, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Tasks</p>
                    <div class="col-md-10" style="width:100%;">
                        @Html.TextBoxFor(model => model.NhiemVu, new { @class = "form-control", @placeholder = "Tasks" })
                        @Html.ValidationMessageFor(model => model.NhiemVu, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Technologies used</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.CongNgheSuDung, new { @class = "form-control", @placeholder = "NodeJS, ASP.NET,..." })
                        @Html.ValidationMessageFor(model => model.CongNgheSuDung, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="d-flex flex-row justify-content-between">
                    <div id="kinhNghiemnBatDau" class="d-flex justify-content-between" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Month start</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangBatDau, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Select month", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ThangBatDau, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title">Start year</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        int currentYear = DateTime.Now.Year;
                                        int startYear = currentYear - 100;
                                        List<SelectListItem> years = new List<SelectListItem>();
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamBatDau, years, "Select year", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.NamBatDau, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamBatDau, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div id="kinhNghiemKetThuc" class="d-flex justify-content-between boxKetThuc" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Finish month</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangKetThuc, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Select month", new { @class = "form-control thangKetThuc" })
                                @Html.ValidationMessageFor(model => model.ThangKetThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title">Finish year</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamKetThuc, years, "Select year", new { @class = "form-control namKetThuc" })
                                    @Html.ValidationMessageFor(model => model.NamKetThuc, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamKetThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <p class="label-title">Description</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextAreaFor(model => model.MoTaChiTiet, new { @class = "form-control pt-2", @placeholder = "Detailed description" })
                        @Html.ValidationMessageFor(model => model.MoTaChiTiet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-2">
                    <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                        <input type="submit" value="Complete" class="btn btn-primary" style="border-radius: 4px;" />
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    { Html.RenderAction("Login", "User"); }
}